BLANK_TILE = $AF
LETTERS_BASE = $B0
NUMBERS_BASE = $E4
SYMBOLS_BASE = $EE

.charmap 32, BLANK_TILE ; " "

.charmap 65, (LETTERS_BASE + 0) ; A
.charmap 66, (LETTERS_BASE + 1) ; B
.charmap 67, (LETTERS_BASE + 2) ; C
.charmap 68, (LETTERS_BASE + 3) ; D
.charmap 69, (LETTERS_BASE + 4) ; E
.charmap 70, (LETTERS_BASE + 5) ; F
.charmap 71, (LETTERS_BASE + 6) ; G
.charmap 72, (LETTERS_BASE + 7) ; H
.charmap 73, (LETTERS_BASE + 8) ; I
.charmap 74, (LETTERS_BASE + 9) ; J
.charmap 75, (LETTERS_BASE + 10) ; K
.charmap 76, (LETTERS_BASE + 11) ; L
.charmap 77, (LETTERS_BASE + 12) ; M
.charmap 78, (LETTERS_BASE + 13) ; N
.charmap 79, (LETTERS_BASE + 14) ; O
.charmap 80, (LETTERS_BASE + 15) ; P
.charmap 81, (LETTERS_BASE + 16) ; Q
.charmap 82, (LETTERS_BASE + 17) ; R
.charmap 83, (LETTERS_BASE + 18) ; S
.charmap 84, (LETTERS_BASE + 19) ; T
.charmap 85, (LETTERS_BASE + 20) ; U
.charmap 86, (LETTERS_BASE + 21) ; V
.charmap 87, (LETTERS_BASE + 22) ; W
.charmap 88, (LETTERS_BASE + 23) ; X
.charmap 89, (LETTERS_BASE + 24) ; Y
.charmap 90, (LETTERS_BASE + 25) ; Z

.charmap 97,  (LETTERS_BASE + 26) ; a
.charmap 98,  (LETTERS_BASE + 27) ; b
.charmap 99,  (LETTERS_BASE + 28) ; c
.charmap 100, (LETTERS_BASE + 29) ; d
.charmap 101, (LETTERS_BASE + 30) ; e
.charmap 102, (LETTERS_BASE + 31) ; f
.charmap 103, (LETTERS_BASE + 32) ; g
.charmap 104, (LETTERS_BASE + 33) ; h
.charmap 105, (LETTERS_BASE + 34) ; i
.charmap 106, (LETTERS_BASE + 35) ; j
.charmap 107, (LETTERS_BASE + 36) ; k
.charmap 108, (LETTERS_BASE + 37) ; l
.charmap 109, (LETTERS_BASE + 38) ; m
.charmap 110, (LETTERS_BASE + 39) ; n
.charmap 111, (LETTERS_BASE + 40) ; o
.charmap 112, (LETTERS_BASE + 41) ; p
.charmap 113, (LETTERS_BASE + 42) ; q
.charmap 114, (LETTERS_BASE + 43) ; r
.charmap 115, (LETTERS_BASE + 44) ; s
.charmap 116, (LETTERS_BASE + 45) ; t
.charmap 117, (LETTERS_BASE + 46) ; u
.charmap 118, (LETTERS_BASE + 47) ; v
.charmap 119, (LETTERS_BASE + 48) ; w
.charmap 120, (LETTERS_BASE + 49) ; x
.charmap 121, (LETTERS_BASE + 50) ; y
.charmap 122, (LETTERS_BASE + 51) ; z


.charmap 48, (NUMBERS_BASE + 0) ; 0
.charmap 49, (NUMBERS_BASE + 1) ; 1
.charmap 50, (NUMBERS_BASE + 2) ; 2
.charmap 51, (NUMBERS_BASE + 3) ; 3
.charmap 52, (NUMBERS_BASE + 4) ; 4
.charmap 53, (NUMBERS_BASE + 5) ; 5
.charmap 54, (NUMBERS_BASE + 6) ; 6
.charmap 55, (NUMBERS_BASE + 7) ; 7
.charmap 56, (NUMBERS_BASE + 8) ; 8
.charmap 57, (NUMBERS_BASE + 9) ; 9

.charmap 44, (SYMBOLS_BASE + 0)  ; ,
.charmap 46, (SYMBOLS_BASE + 1)  ; .
.charmap 63, (SYMBOLS_BASE + 2)  ; ?
.charmap 33, (SYMBOLS_BASE + 3)  ; !
.charmap 34, (SYMBOLS_BASE + 4)  ; "
.charmap 39, (SYMBOLS_BASE + 5)  ; '
.charmap 40, (SYMBOLS_BASE + 6)  ; (
.charmap 41, (SYMBOLS_BASE + 7)  ; )
.charmap 91, (SYMBOLS_BASE + 8)  ; [
.charmap 93, (SYMBOLS_BASE + 9)  ; ]
.charmap 58, (SYMBOLS_BASE + 10) ; :
.charmap 59, (SYMBOLS_BASE + 11) ; ;
.charmap 42, (SYMBOLS_BASE + 12) ; *
.charmap 94, (SYMBOLS_BASE + 13) ; ^
.charmap 95, (SYMBOLS_BASE + 14) ; _
.charmap 64, (SYMBOLS_BASE + 15) ; @
.charmap 62, (SYMBOLS_BASE + 16) ; >
.charmap 60, (SYMBOLS_BASE + 17) ; <

.charmap 45, $A9 ; -
.charmap 47, $AA ; /

